print 'Content-Type: text/plain'
print ''
print 'Hello, world!'
print 'hmm can't think of anything interesting'
print 'hello pdog 2'
print 'hello dru, kick it one time yo!'
print 'dont fake the funk on a nasty dunk'